title: KeeganJin Blog
description: 用 Markdown 记录日常、技术和思考
url: "https://keeganjin.github.io"
baseurl: ""
timezone: Asia/Shanghai
lang: zh-CN

markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-feed
